=== public-transport/transport-apis/schema.json
{
  "$id": "https://raw.githubusercontent.com/public-transport/transport-apis/v1/schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "public transport API description",
  "type": "object",
  "required": [
    "name",
    "type",
    "supportedLanguages",
    "coverage",
    "options"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "type": {
      "type": "object",
      "propertyNames": {
        "enum": [
          "efa",
          "hafasMgate",
          "hafasQuery",
          "navitia",
          "otpGraphQl",
          "otpRest"
        ]
      },
      "additionalProperties": {
        "type": "boolean"
      }
    },
    "supportedLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z][a-z]$",
        "description": "ISO-639-1 language code"
      }
    },
    "coverage": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "realtimeCoverage": {
          "$ref": "#/definitions/coverage"
        },
        "regularCoverage": {
          "$ref": "#/definitions/coverage"
        },
        "anyCoverage": {
          "$ref": "#/definitions/coverage"
        }
      }
    },
    "attribution": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/attribution_opendata" },
        { "$ref": "#/definitions/attribution_proprietary" }
      ]
    },
    "options": {
      "type": "object"
    }
  },
  "definitions": {
    "coverage": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "area": {
          "$ref": "#/definitions/coverage_geojson"
        },
        "region": {
          "$ref": "#/definitions/coverage_region"
        }
      }
    },
    "coverage_geojson": {
      "type": "object",
      "required": [
        "type",
        "coordinates"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Polygon"
          ]
        },
        "coordinates": {
          "type": "array",
          "items": {
            "type": "array",
            "minItems": 4,
            "items": {
              "type": "array",
              "minItems": 2,
              "items": {
                "type": "number"
              }
            }
          }
        },
        "bbox": {
          "type": "array",
          "minItems": 4,
          "items": {
            "type": "number"
          }
        }
      }
    },
    "coverage_region": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z][a-zA-Z](-[a-zA-Z][a-zA-Z])?$",
        "description": "ISO-3166-1/2 country/region code"
      },
      "minItems": 1
    },
    "attribution_opendata": {
      "type": "object",
      "required": [
        "license",
        "name"
      ],
      "properties": {
        "license": {
          "type": "string",
          "description": "Open Definition license ID or SPDX license id"
        },
        "name": {
          "type": "string"
        },
        "homepage": {
          "type": "string"
        }
      }
    },
    "attribution_proprietary": {
      "type": "object",
      "required": [
        "isProprietary"
      ],
      "properties": {
        "isProprietary": {
          "type": "boolean"
        }
      }
    }
  }
}

=== public-transport/transport-apis/data/de/vrr-efa.json
{
	"name": "Verkehrsverbund Rhein-Ruhr (VRR)",
	"type": {
		"efa": true
	},
	"coverage": {
		"realtimeCoverage": {
			"area": {
				"coordinates": [
					[ [ 5.8835, 51.9055 ], [ 6.0496, 51.111 ], [ 7.6174, 50.9833 ], [ 7.6207, 51.79 ], [ 5.8835, 51.9055 ] ]
				],
				"type": "Polygon"
			},
			"region": [ "DE-NW" ]
		}
	},
	"supportedLanguages": [
		"en",
		"de"
	],
	"options": {
		"endpoint": "https://efa.vrr.de/standard/",
		"supportedOutputFormats": [ "XML", "JSON" ],
		"xmlOutputFormat": "full"
	}
}

=== public-transport/transport-apis/data/no/entur-otp.json
{
    "name": "Entur",
    "attribution": {
        "license": "Norwegian Licence for Open Government Data (NLOD)",
        "licenseUrl": "https://data.norge.no/nlod/en",
        "name": "Entur",
        "url": "https://www.entur.org/"
    },
    "coverage": {
        "regularCoverage": {
            "area": {
                "coordinates": [ [ [ 5.14553, 58.7711 ], [ 8.5538, 56.8847 ], [ 31.5632, 69.8993 ], [ 25.3899, 85.02453 ], [ -0.1243, 75.9905 ], [ 5.14553, 58.7711 ] ] ],
                "type": "Polygon"
            },
            "region": [ "NO" ]
        }
    },
    "options": {
        "endpoint": "https://api.entur.io/journey-planner/v2/graphql/",
        "apiVersion": "entur"
    },
    "supportedLanguages": [ "no" ],
    "type": {
        "otpGraphQl": true
    }
}

=== public-transport/transport-apis/data/de/gvh-efa.json
{
    "name": "Gro√üraum-Verkehr Hannover (GVH)",
    "coverage": {
        "realtimeCoverage": {
            "area": {
                "coordinates": [
                    [ [ 6.8558, 53.8848 ], [ 6.6065, 52.0076 ], [ 10.7129, 51.0397 ], [ 11.6759, 53.1955 ], [ 9.6178, 53.9532 ], [ 6.8558, 53.8848 ] ]
                ],
                "type": "Polygon"
            },
            "region": [ "DE-NI" ]
        }
    },
    "options": {
        "endpoint": "https://app.efa.de/mdv_server/app_gvh/"
    },
    "supportedLanguages": [ "de", "en" ],
    "type": {
        "efa": true
    }
}

=== public-transport/transport-apis/data/de/bayernfahrplan-efa.json
{
    "name": "Bayern Fahrplan",
    "coverage": {
        "realtimeCoverage": {
            "area": {
                "coordinates": [
                    [ [ 8.7591, 50.5296 ], [ 12.872, 50.66655 ], [ 14.3451, 47.6552 ], [ 9.9063, 46.9968 ], [ 8.7591, 50.5296 ] ]
                ],
                "type": "Polygon"
            },
            "region": [ "DE-BY" ]
        }
    },
    "options": {
        "compactXmlRepsonse": true,
        "endpoint": "https://mobile.defas-fgi.de/beg/"
    },
    "supportedLanguages": [ "de", "en" ],
    "type": {
        "efa": true
    }
}
